Entities table -  WIP PR
geobrowser/geogenesis pull request #139
Opened 2022-12-20 17:53 UTC by makeitrein

Displays the upcoming entities table on the `/entities` route

2022-12-22 22:21 UTC, baiirun commented on apps/web/modules/components/entity-table/entity-table-container.tsx
> +      <motion.div style={{ maxWidth: '100%' }} layout="position" transition={{ duration: 0.1 }}>
We probably don't need this layout animation wrapper since we aren't doing any animations on the table.

2022-12-22 22:21 UTC, baiirun commented on apps/web/modules/components/entity-table/entity-table.tsx
> +    }, [initialCellData]);
You should be able to remove this code if you want since it's related to cell editing. Instead of using `cellData` in the rest of the function you can use `initialCellData`, or just rename `initialCellData` to `cellData`

2022-12-22 22:21 UTC, baiirun commented on apps/web/modules/constants.ts
> +  SCHEMA_TYPE: 'd7ab4092-0ab5-441e-88c3-5c27952de773',
🔥

2022-12-22 22:21 UTC, baiirun commented on apps/web/modules/components/triple-table.tsx
> +                </TableHead>
Did you mean to rename this to TableHead when you moved it out of this file?

2022-12-22 22:21 UTC, baiirun commented on apps/web/modules/components/entity-table/entity-table.tsx
> +          if (attributeId === 'name') {
Should we be using the `columnId` to determine what to render instead of the `attributeId`?

2022-12-22 22:21 UTC, baiirun commented on apps/web/modules/components/space/space-navbar.tsx
> +      <div>
Can we use `gap` or a `Spacer` here instead of encoding spacing in the `TabLink` component?

2022-12-22 22:21 UTC, baiirun commented on apps/web/modules/design-system/tab-link.tsx
> +  paddingRight: `${theme.space * 4}px`,
See the comment in [space-navbar](apps/web/modules/components/space/space-navbar.tsx)

2022-12-22 22:21 UTC, baiirun commented on apps/web/modules/services/network.ts
> +    const columnsTriples = await new Network(storage, subgraph).fetchTriples({
Now that I'm seeing this here I don't like it. We're having to instantiate a new network inside of the Network in order to avoid cancellation. We can leave it for now to get this merged, but let's figure out how we want to solve this before we release this feature to the wild.

2022-12-22 22:21 UTC, baiirun commented on apps/web/modules/services/network.ts
> +      await new Network(storage, subgraph).fetchTriples({
Can we put this network call and the one on line 312 together in a `Promise.all` so they happen in parallel?

2022-12-22 22:21 UTC, baiirun commented on packages/subgraph/src/bootstrap.ts
> +  handleAction(new CreateEntityAction(SCHEMA_TYPE_ID), space, createdAtBlock)
We should redeploy the subgraph after we merge so these get created with the correct ID in every space.

2022-12-22 22:58 UTC, makeitrein commented on apps/web/modules/components/entity-table/entity-table-container.tsx
> +      <motion.div style={{ maxWidth: '100%' }} layout="position" transition={{ duration: 0.1 }}>
👍 Resolved

2022-12-22 23:00 UTC, makeitrein commented on apps/web/modules/components/entity-table/entity-table.tsx
> +    }, [initialCellData]);
Is it worth keeping if table editing will next on our docket? Definitely want to pick your brain about how you structured the table editing for the triples table when that feature existed

2022-12-22 23:00 UTC, makeitrein commented on apps/web/modules/components/triple-table.tsx
> +                </TableHead>
Excellent catch

2022-12-22 23:02 UTC, makeitrein commented on apps/web/modules/components/entity-table/entity-table.tsx
> +          if (attributeId === 'name') {
yup, that feels more descriptive of what's actually going on - resolved

2022-12-22 23:09 UTC, makeitrein commented on apps/web/modules/components/space/space-navbar.tsx
> +      <div>
Yup agreed - outside component should be responsible for managing spacing

2022-12-22 23:09 UTC, makeitrein commented on apps/web/modules/design-system/tab-link.tsx
> +  paddingRight: `${theme.space * 4}px`,
^^ Done

2022-12-22 23:09 UTC, makeitrein commented on apps/web/modules/services/network.ts
> +    const columnsTriples = await new Network(storage, subgraph).fetchTriples({
Agreed, this can be the area of first refactor

2022-12-22 23:13 UTC, makeitrein commented on apps/web/modules/services/network.ts
> +      await new Network(storage, subgraph).fetchTriples({
Nice optimization 👍

2022-12-22 23:14 UTC, makeitrein commented on packages/subgraph/src/bootstrap.ts
> +  handleAction(new CreateEntityAction(SCHEMA_TYPE_ID), space, createdAtBlock)
Agreed, also need to bootstrap all of those other custom types like VALUE_TYPE, RELATION_TYPES, and MULTIPLE_ALLOWED

2022-12-23 13:50 UTC, baiirun commented on apps/web/modules/components/entity-table/entity-table.tsx
> +    }, [initialCellData]);
I'd probably remove it for now just to simplify the code for now. It's easy enough to add it back whenever we get to editing.

2022-12-23 13:56 UTC, baiirun requested changes

2022-12-23 13:56 UTC, baiirun commented on apps/web/pages/space/[id]/entities.tsx
> +  const initialSelectedType =
I'd opt to set `initialSelectedType` to `null` if there's no initial type selected. We can figure out how we want to handle this on the client. Maybe we just select the first type in the list instead.

This works basically the same as the blessed `notFoundType` Triple, but without having to encode what the `notFoundType` means on the client and server.

2022-12-23 13:56 UTC, baiirun commented on apps/web/pages/space/[id]/entities.tsx
> +        initialSelectedType={initialSelectedType}
For example, here we can default to the first type in the list of there's no initial type selected. Maybe it makes sense to that on the server as well instead of on the client 🤔

2022-12-23 19:35 UTC, makeitrein commented on apps/web/modules/components/entity-table/entity-table.tsx
> +    }, [initialCellData]);
Done!

2022-12-23 20:05 UTC, makeitrein commented on apps/web/pages/space/[id]/entities.tsx
> +        initialSelectedType={initialSelectedType}
Made initialSelectedType nullable - feels like a decent paradigm, what say you good ser?

2023-01-03 18:17 UTC, baiirun approved these changes

2023-01-03 18:20 UTC, merged