Entity autofill v2
geobrowser/geogenesis pull request #165
Opened 2023-01-07 00:44 UTC by MercuricChloride

Gonna wrap this up on with entity schema defaults selection on Monday.

2023-01-09 15:56 UTC, baiirun requested changes
Looks good. We should also add some tests for all of the placeholder-related code.
- Tests in the`EntityStore` to ensure `typeTriples` and `schemaTriples` populated as expected. You can use the `MockNetwork` to test `schemaTriples` without using the real subgraph.
- Tests to make sure we're rendering the correct UI for the placeholder vs. non-placeholder fields. And that manipulating one or the other correctly updates the UI.

2023-01-09 15:56 UTC, baiirun commented on apps/web/modules/entity/entity-store.tsx
> +          .map(triple => ({
We can use `flatMap` here if we really want to save a loop. Probably doesn't matter in most cases since there's not many schemaTypes for a given type.

2023-01-09 15:56 UTC, baiirun commented on apps/web/modules/components/entity/editable-entity-page.tsx
> +  const [deletedPlaceholders, setDeletedPlaceholders] = useState<string[]>([]);
Does it make more sense to keep deletedPlaceholders in the EntityStore? Right now most of our state lives in the EntityStore so it's a little confusing for some of it to live in React state and some to live in EntityState, especially since we're already tracking placeholder-related state in the store.

2023-01-09 15:56 UTC, baiirun commented on apps/web/modules/components/entity/editable-entity-page.tsx
> +  const unusedSchemaTriples = schemaTriples.filter(t => !triples.some(t2 => t2.attributeId === t.attributeId));
Can we use more meaningful names for the triples in these callbacks? Like `schemaTriple` and `triple` or something.

2023-01-09 15:56 UTC, baiirun commented on apps/web/modules/components/entity/edit-events.ts
> +    console.log(event);
Can remove this lil guy

2023-01-10 22:23 UTC, MercuricChloride commented
Just an fyi, still working out these bugs, these changes aren't the final submission for this PR

2023-01-11 20:49 UTC, baiirun reviewed
Looks good. Had a few questions

2023-01-11 20:49 UTC, baiirun commented on apps/web/modules/components/entity/editable-entity-page.tsx
> +  deletedSchemaIds: (String | undefined)[];
Should this be lowercase `string | undefined`? We can also filter out the `undefined` values if that makes more sense.

2023-01-11 20:49 UTC, baiirun commented on apps/web/modules/components/entity/editable-entity-page.tsx
> +            placeholder="String value!"
We should change this back to "Add value..."

2023-01-11 20:49 UTC, baiirun commented on apps/web/modules/components/entity/editable-entity-page.tsx
> +        console.log('TRIPLES PER GROUP', triples);
Can get rid of this lil guy

2023-01-11 20:49 UTC, baiirun commented on apps/web/modules/entity/entity-store.tsx
> +          .filter(triple => !deletedSchemaIds.includes(triple.attributeId))
Is this related to the `@goose` comment in `editable-entity-page`? If so we should probably just do one or the other instead of both.

2023-01-11 20:49 UTC, baiirun commented on apps/web/modules/entity/entity-store.tsx
> +  deletedSchemaIds$: Observable<String[]> = observable<String[]>([]);
Should this be lowercase `string`?

2023-01-11 21:16 UTC, makeitrein commented on apps/web/modules/components/entity/editable-entity-page.tsx
> +  deletedSchemaIds: (String | undefined)[];
Done!

2023-01-11 21:16 UTC, makeitrein commented on apps/web/modules/components/entity/editable-entity-page.tsx
> +        console.log('TRIPLES PER GROUP', triples);
Removed all logs!

2023-01-11 21:17 UTC, makeitrein commented on apps/web/modules/entity/entity-store.tsx
> +  deletedSchemaIds$: Observable<String[]> = observable<String[]>([]);
Yup yup

2023-01-11 21:18 UTC, makeitrein commented on apps/web/modules/entity/entity-store.tsx
> +          .filter(triple => !deletedSchemaIds.includes(triple.attributeId))
Which comment are you referring to?

2023-01-12 17:44 UTC, makeitrein commented on apps/web/modules/components/entity/editable-entity-page.tsx
> +  const unusedSchemaTriples = schemaTriples.filter(t => !triples.some(t2 => t2.attributeId === t.attributeId));
Done!

2023-01-12 20:17 UTC, baiirun commented on apps/web/modules/components/entity/editable-entity-page.test.tsx
> +import { render, screen } from '@testing-library/react';
🔥

2023-01-12 20:23 UTC, baiirun reviewed
Looking really good! Just a couple small comments

2023-01-12 20:23 UTC, baiirun commented on apps/web/modules/components/entity/editable-entity-page.tsx
> +  const sortedTriples = filteredTriples.sort((tripleA, tripleB) => {
Can we move this to its own function? Would make this component more scannable without having to scroll past 40 lines of sorting code. Would make it possible to test this sorting algo as well.

2023-01-12 20:23 UTC, baiirun commented on apps/web/modules/components/entity/editable-entity-page.tsx
> +                            <Text variant="button">Relation</Text>
can you change the labels back to not have the `Text` component wrapping the field? It'll break styling of the type dropdown.

2023-01-12 20:23 UTC, baiirun commented on apps/web/modules/components/entity/editable-entity-page.tsx
> -                          Relation
Related to X: The field label should look like this

2023-01-12 20:23 UTC, baiirun commented on apps/web/modules/entity/entity-store.test.ts
> +import { when } from '@legendapp/state';
🔥

2023-01-12 20:23 UTC, baiirun commented on apps/web/modules/entity/entity-store.tsx
> +      return typeIds;
Might be worth adding a comment as to why we're using `observe` here instead of `computed`

2023-01-12 20:55 UTC, makeitrein commented on apps/web/modules/entity/entity-store.tsx
> +      return typeIds;
Good call, adding now...

2023-01-12 21:08 UTC, makeitrein commented on apps/web/modules/components/entity/editable-entity-page.tsx
> +  const sortedTriples = filteredTriples.sort((tripleA, tripleB) => {
Agreed, good call

2023-01-12 21:08 UTC, makeitrein commented on apps/web/modules/components/entity/editable-entity-page.tsx
> +                            <Text variant="button">Relation</Text>
Yup, mucked up during a merge

2023-01-12 21:11 UTC, makeitrein commented on apps/web/modules/components/entity/editable-entity-page.tsx
> -                          Relation
Good catch

2023-01-13 19:47 UTC, baiirun approved these changes
🎉

2023-01-13 19:55 UTC, merged