Linkable chips awaiting design
geobrowser/geogenesis pull request #177
Opened 2023-01-10 20:51 UTC by makeitrein

<img width="312" alt="image" src="https://user-images.githubusercontent.com/2068463/211660054-6b16dbe5-8736-490d-b476-f875bedb71f3.png">

2023-01-10 21:00 UTC, baiirun requested changes

2023-01-10 21:00 UTC, baiirun commented on apps/web/modules/design-system/chip.tsx
> +        <div onClick={onClick}>
Can we change this to a button for accessiblity reasons? May just have to make it completely unset. We have an `IconButton` in the design system button but it's not very flexible atm.

2023-01-10 21:00 UTC, baiirun commented on apps/web/modules/components/entity-table/editable-entity-table-cell.tsx
> +              onClick={() => removeOrResetEntityTriple(triple)}
Can we rename this to onDeleteClick or something different to differentiate it from clicking the entire chip?

2023-01-10 21:02 UTC, makeitrein commented on apps/web/modules/components/entity-table/editable-entity-table-cell.tsx
> +              onClick={() => removeOrResetEntityTriple(triple)}
Yup, worth just renaming this component to DeleteChipButton? ChipButton not currently being used in any other context

2023-01-10 21:32 UTC, baiirun commented on apps/web/modules/components/entity-table/editable-entity-table-cell.tsx
> +              onClick={() => removeOrResetEntityTriple(triple)}
Sounds good to me. Or EditableChipButton or something. I like DeletableChipButton.

2023-01-12 19:18 UTC, makeitrein commented on apps/web/modules/design-system/chip.tsx
> +        <div onClick={onClick}>
Updated!

2023-01-12 20:53 UTC, baiirun approved these changes
🚀

2023-01-12 20:54 UTC, merged