Onboarding profile
geobrowser/geogenesis pull request #214
Opened 2023-02-16 21:26 UTC by makeitrein

2023-02-16 23:14 UTC, baiirun requested changes

2023-02-16 23:14 UTC, baiirun commented on apps/web/modules/onboarding/dialog.tsx
> +      <div className="text-center pb-4 text-smallTitle -mt-6">{name}</div>
This should probably be some sort of header for accessibility reasons.

2023-02-16 23:14 UTC, baiirun commented on apps/web/modules/onboarding/dialog.tsx
> +      <div className="text-bodySemibold text-xl text-center">
This should be some sort of header. We also still have the `Text` component for text variants.

2023-02-16 23:14 UTC, baiirun commented on apps/web/modules/onboarding/dialog.tsx
> +  const validName = name.length > 3;
Was this a product requirement?

2023-02-16 23:14 UTC, baiirun commented on apps/web/modules/onboarding/dialog.tsx
> +          <input accept="image/png, image/jpeg" onChange={handleChange} type="file" className="hidden" />
Shouldn't the input be outside of the label? They should be siblings.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label

2023-02-16 23:14 UTC, baiirun commented on apps/web/modules/onboarding/dialog.tsx
> +    <>
Do we need this fragment?

2023-02-16 23:14 UTC, baiirun commented on apps/web/modules/onboarding/dialog.tsx
> +            <div className="text-largeTitle -mt-1">GEO</div>
Same comment as some of the others. Let's make sure we're using semantic HTML elements. We can use the `Text` element if we want.

2023-02-16 23:14 UTC, baiirun commented on apps/web/modules/onboarding/dialog.tsx
> +        <div className={`rotate-180`}>
Shouldn't need the curly bois here.

2023-02-16 23:14 UTC, baiirun commented on apps/web/modules/onboarding/dialog.tsx
> +  ];
Another way to do this is to name the steps to something semantic.

```tsx
type Steps = "wallet" | "name" | "avatar" | "success"

const [step, setStep] = useStep<Steps>("wallet");
```

Then we can pass in which step that `nextStep` should go to.

```tsx
<StepWallet onNext={() => setStep("name")} onPrevious={undefined} address={address} key="wallet" />
<StepName onNext={() => setStep("avatar")} onPrevious={() => setStep("wallet") address={address} key="wallet" />,
```

This is nice since you don't need all the error checks for the step index value and it's pretty clear how each step progresses to the next or previous. We do the same thing in `FlowBar`

2023-02-16 23:14 UTC, baiirun commented on apps/web/modules/onboarding/use-onboarding.tsx
> +  const isOnboardingVisible = useObservable(false);
Any reason we're using `useObservable` here instead of regular React state?

2023-02-18 00:02 UTC, makeitrein commented on apps/web/modules/onboarding/dialog.tsx
> +  ];
Yee, cleaned it up

2023-02-18 00:03 UTC, makeitrein commented on apps/web/modules/onboarding/dialog.tsx
> +  const validName = name.length > 3;
Nope, made it a minimum length of 1. There is a product requirement of a disabled state w/ no text.

2023-02-27 18:01 UTC, baiirun commented on apps/web/modules/design-system/icons/close.tsx
> +}
I think this will get invalidated by @sandren's changes since we won't have the `emotion/react` package anymore.

2023-02-27 18:02 UTC, baiirun commented on apps/web/modules/onboarding/use-onboarding.tsx
> +  return { isOnboardingVisible, hideOnboarding };
Let's wrap the `isOnboardingVisible` in a `useSelector`. This is so we don't expose the observable to our React components. By exposing the observable all of the components consuming the observable have to do `.get()` to unwrap the value. 

Check out `use-editable` for an example.

2023-02-27 18:03 UTC, baiirun commented on apps/web/modules/utils.ts
> +export function formatAddress(address: string): string {
Maybe a better name for this is `formatShortAddress` or something similar.

2023-02-27 22:23 UTC, makeitrein commented on apps/web/modules/design-system/icons/close.tsx
> +}
Yup removed!

2023-02-27 22:23 UTC, makeitrein commented on apps/web/modules/onboarding/use-onboarding.tsx
> +  return { isOnboardingVisible, hideOnboarding };
Got it

2023-02-27 22:23 UTC, makeitrein commented on apps/web/modules/utils.ts
> +export function formatAddress(address: string): string {
Updated

2023-03-01 18:53 UTC, baiirun commented on apps/web/modules/onboarding/dialog.tsx
> +    <Command.Dialog open={false} label="Onboarding profile">
There's a known bug in here somewhere that Nate discovered when disconnecting and reconnecting your wallet. We can revisit later when we're ready to integrate Profiles on the backend.

2023-03-01 20:13 UTC, merged