Editable column type
geobrowser/geogenesis pull request #224
Opened 2023-02-24 19:25 UTC by makeitrein

2023-02-27 21:32 UTC, makeitrein commented on apps/web/modules/action/action.test.ts
No more squashing as per convo with @baiirun

2023-02-27 21:32 UTC, makeitrein commented on apps/web/modules/action/action.ts
No more squashing

2023-02-27 21:32 UTC, makeitrein commented on apps/web/modules/action/actions-store.ts
>        await this.api.publish({
No more squashing...

2023-02-27 21:32 UTC, makeitrein commented on apps/web/modules/components/debug/debug-actions.tsx
> +export const DebugActions = ({
Useful dev tool component for displaying actions in popover

2023-02-27 21:32 UTC, makeitrein commented on apps/web/modules/components/debug/debug-object.tsx
> +export const DebugObject = ({
Useful dev tool for displaying an object in a popover, currently not used in code base but is helpful once in a blue moon

2023-02-27 21:32 UTC, makeitrein commented on apps/web/modules/components/debug/debug-popover.tsx
> +
Popover responsible for displaying triples/object/actions

2023-02-27 21:32 UTC, makeitrein commented on apps/web/modules/components/debug/debug-triples.tsx
> +export const DebugTriples = ({
This is the most useful dev tool component! Added to each of the entity table cells to see what's actually being used...

2023-02-27 21:32 UTC, makeitrein commented on apps/web/modules/components/entity-table/editable-entity-table-cell.tsx
> +  triples,
We actually merge all server and local triples together in the entity-table.tsx component, so it doesn't make sense to include serverTriple logic here anymore.

2023-02-27 21:32 UTC, makeitrein commented on apps/web/modules/components/entity-table/editable-entity-table-cell.tsx
> -  const groupedTriples = groupBy(triples, t => t.attributeId);
We also filter triples by the appropriate attributeId in the entity-table as well, can remove this attributeId logic as well

2023-02-27 21:32 UTC, makeitrein commented on apps/web/modules/components/entity-table/editable-entity-table-cell.tsx
> -        isLastEntity: groupedTriples[triple.attributeId].length === 1,
There's now a REMOVE_ENTITY action for a straightforward triple removal and a REMOVE_PAGE_ENTITY to handle the UX edge case in the editable entity page.

2023-02-27 21:32 UTC, makeitrein commented on apps/web/modules/components/entity-table/editable-entity-table-cell.tsx
> -  const tripleToEditableField = (attributeId: string, triple: Triple, isEmptyEntity: boolean) => {
I found this map function a bit overkill since it was used only for the entity use case.

2023-02-27 21:49 UTC, makeitrein commented on apps/web/modules/components/entity-table/editable-entity-table-cell.tsx
> +      type: 'CREATE_ENTITY_TRIPLE_WITH_VALUE',
Similarly, ADD_PAGE_ENTITY_VALUE is PAGE specific while CREATE_ENTITY_TRIPLE_WITH_VALUE is designed to be more general.

2023-02-27 21:49 UTC, makeitrein commented on apps/web/modules/components/entity-table/editable-entity-table-column-header.tsx
> +  const localTriples = pipe(
Since we're controlling the value type of the column, we have to do some ceremony to get the unpublished triples related to this column now

2023-02-27 21:49 UTC, makeitrein commented on apps/web/modules/components/entity-table/entity-table-cell.tsx
> +export const EntityTableCell = ({ cell, triples, space, isExpanded }: Props) => {
We want to ensure that the both browse and edit cells share identical triples - we filter and merge local triples with server triples for cells in entity-table.tsx now.

2023-02-27 21:49 UTC, makeitrein commented on apps/web/modules/components/entity-table/entity-table.tsx
> +      A.filter(triple => {
Here we make the decision to only show cells of the column's value type - this might cause some display issues in prod for columns that have no value types set since we default to TEXT.

2023-02-27 21:49 UTC, makeitrein commented on apps/web/modules/components/entity-table/entity-table.tsx
> -            const initialTriples = cells
Unused code

2023-02-27 21:49 UTC, makeitrein commented on apps/web/modules/components/entity/edit-events.ts
> +            attributeId: attributeId,
Switched to passing in the attributeId and attributeName directly since we no longer have placeholder triples in table cells

2023-02-27 21:49 UTC, makeitrein commented on apps/web/modules/components/entity/editable-fields.tsx
> +  useEffect(() => {
This change was required because the 'CHANGE_COLUMN_VALUE_TYPE' will set the name of string fields from outside the component.

2023-02-27 21:49 UTC, makeitrein commented on apps/web/modules/entity/entity-table-store/Table.ts
> +      const cellTriples = triplesForAttribute.length ? triplesForAttribute : [];
No more placeholder triple!

2023-02-27 21:49 UTC, makeitrein commented on apps/web/modules/entity/entity-table-store/entity-table-store.ts
> +    this.unpublishedColumns$ = computed(() => {
We need this to ensure that only unpublished columns can change their value types (for now...)

2023-02-27 21:51 UTC, makeitrein commented on apps/web/modules/components/navbar/navbar.tsx
> +        <DebugActions spaceId={spaceId ?? ''} />
Now we can see the actions in dev mode

2023-03-01 19:02 UTC, baiirun commented
@makeitrein Looks like the padding for the entity table column is way off in edit mode resulting in this weird offset on the add column button. Should look like the bottom image from Figma.
<img width="1244" alt="CleanShot 2023-03-01 at 12 01 35@2x" src="https://user-images.githubusercontent.com/26263630/222238668-ed471e90-f217-4f4e-984b-024be752bb27.png">
<img width="447" alt="CleanShot 2023-03-01 at 12 01 01@2x" src="https://user-images.githubusercontent.com/26263630/222238704-f0c0328e-973a-45e0-b6d0-34a7fe8b33b9.png">

2023-03-01 19:18 UTC, baiirun requested changes

2023-03-01 19:18 UTC, baiirun commented on apps/web/modules/components/debug/debug-popover.tsx
> +  },
Can you convert all these to tailwind? @sandren has a PR where we're removing all styled component usage. Might be worth merging her PR in first and you can copy over the dialog code and use it in the debugger components.

2023-03-01 19:18 UTC, baiirun commented on apps/web/modules/components/debug/debug-triples.tsx
> +export const DebugTriples = ({
Is there a way to remove the tool by default? I imagine we probably only want to render the debug triples sometimes when specifically wanting to debug things.

2023-03-01 19:18 UTC, baiirun commented on apps/web/modules/components/entity-table/entity-table.tsx
> +          <div className={cx('flex items-center justify-between', isLastColumn ? 'pr-12' : '')}>
What is this flex layout doing? There's only the one child AFAICT

2023-03-01 19:18 UTC, baiirun commented on apps/web/modules/components/entity-table/entity-table.tsx
> +      A.filter(triple => {
How are we solving for this display issue?

2023-03-01 19:18 UTC, baiirun commented on apps/web/modules/entity/entity.ts
> +export function valueType(triples: TripleType[]): string | null {
I'd probably call this `valueTypeId`

2023-03-01 19:18 UTC, baiirun commented on apps/web/modules/value/value.ts
> +export function nameOfStringValue(triple: Triple) {
This isn't really a nameOfStringValue, it's just a stringValue

2023-03-01 20:34 UTC, makeitrein commented on apps/web/modules/components/entity-table/entity-table.tsx
> +          <div className={cx('flex items-center justify-between', isLastColumn ? 'pr-12' : '')}>
Done!

2023-03-01 20:41 UTC, makeitrein commented on apps/web/modules/value/value.ts
> +export function nameOfStringValue(triple: Triple) {
Done!

2023-03-01 20:41 UTC, makeitrein commented on apps/web/modules/entity/entity.ts
> +export function valueType(triples: TripleType[]): string | null {
Done!

2023-03-01 20:41 UTC, makeitrein commented on apps/web/modules/components/debug/debug-popover.tsx
> +  },
Yup, converted

2023-03-01 20:57 UTC, baiirun approved these changes

2023-03-01 21:19 UTC, merged