feat: page editor
geobrowser/geogenesis pull request #240
Opened 2023-03-20 01:36 UTC by makeitrein

2023-03-20 04:00 UTC, makeitrein commented on apps/web/modules/components/entity-table/entity-input.tsx
> +      <TypeDialogPopover inputContainerWidth={Math.min(inputRect?.width || 0, 678)} spaceId={spaceId} />
Separating out the TypeDialog from it's popover so we can also use it in the editor

2023-03-20 04:00 UTC, makeitrein commented on apps/web/modules/components/entity-table/entity-table-container.tsx
> +        {showHeader && (
Might need to rename showHeader down the line to editorMode or some such thing...

2023-03-20 04:00 UTC, makeitrein commented on apps/web/modules/components/entity-table/entity-table.tsx
>    const { isEditor } = useAccessControl(space);
Memoizing a few things since I was dealing with excessive rerenders of the Table component

2023-03-20 04:00 UTC, makeitrein commented on apps/web/modules/components/entity/editor/command-list.tsx
> +  useImperativeHandle(ref, () => ({
We should probably add this keyboard navigation to the TypeDialog in a future PR

2023-03-20 04:00 UTC, makeitrein commented on apps/web/modules/components/entity/editor/editor.tsx
> +    [editable]
useEditor takes a dependency array - I think there's potential for problems if entityStore.editorJson isn't fully hydrated by the time we reach this point. 

We don't always want editorJson as a dependency however, since it will update onBlur and defocus and close our command popover triggered by the "/" or the "+" button. 

Will know if this is a problem once we put it into our actual entity page.

2023-03-20 04:00 UTC, makeitrein commented on apps/web/modules/components/entity/editor/editor.tsx
> +          <SquareButton onClick={() => editor.chain().focus().insertContent('/').run()} icon="plus" />
A bit of a hack to open up the command menu, but dealing with the internals of Prosemirror can be very annoying.

2023-03-20 04:00 UTC, makeitrein commented on apps/web/modules/components/entity/editor/id-extension.tsx
> +            keepOnSplit: false,
keepOnSplit makes sure that IDs don't stay the same when you click the enter key for a pargraph

2023-03-20 04:00 UTC, makeitrein commented on apps/web/modules/components/entity/editor/id-extension.tsx
> +  onBlur() {
This onBlur fires before the editor's onBlur and sets the IDs of each new node.

2023-03-20 04:00 UTC, makeitrein commented on apps/web/modules/components/entity/editor/table-node.tsx
> +export const TableNodeChildren = React.memo(function TableNodeComponent({
Was running into a lot of excessive rerendering of the table, went ham on memoization to address the issue

2023-03-20 04:00 UTC, makeitrein commented on apps/web/modules/components/filter/type-dialog.tsx
A bit of work here done to generalize the TypeDialog so it can be used in both the table and editor context

2023-03-20 04:01 UTC, makeitrein commented on apps/web/pages/space/[id]/[entityId].tsx
> +      name={props.name}
Name and the blockIdsTriple and blockTriples are now attributes of EntityStoreProvider

Perhaps name should be computed off triples, would that be cleaner @baiirun

2023-03-20 17:43 UTC, baiirun requested changes

2023-03-20 17:43 UTC, baiirun commented on apps/web/modules/components/entity/editor/command-extension.tsx
> +        .filter(v => v.command)
What is this filter doing? Don't all our commands in `command-items` have a command?

2023-03-20 17:43 UTC, baiirun commented on apps/web/modules/components/entity/editor/command-extension.tsx
> +        },
Can we somehow use Radix's popover elements instead of bringing in a new dependency?

2023-03-20 17:43 UTC, baiirun commented on apps/web/modules/components/entity/editor/command-list.tsx
> +  const tableItem = items.find(item => item.title === 'Table') as CommandSuggestionItem;
Could this ever return undefined? When casting like this we gotta be careful that we aren't accidentally hiding a bug.

2023-03-20 17:43 UTC, baiirun commented on apps/web/modules/components/entity/editor/command-list.tsx
> +    if (!item) {
When would we not pass an item? Based on the type parameter I'd expect it to always be non-null/undefined.

2023-03-20 17:43 UTC, baiirun commented on apps/web/modules/components/entity/editor/command-list.tsx
> +  useImperativeHandle(ref, () => ({
Why are we using `useIMperativeHandle` instead of a `useEffect`?

2023-03-20 17:43 UTC, baiirun commented on apps/web/modules/components/entity/editor/command-list.tsx
> +    }
Why do we need this?

2023-03-20 17:43 UTC, baiirun commented on apps/web/modules/components/entity/editor/editor.tsx
> +          <SquareButton onClick={() => editor.chain().focus().insertContent('/').run()} icon="plus" />
Can you turn this into a function called `openCommandMenu` or something so it's clear what this chain of calls does?

2023-03-20 17:43 UTC, baiirun commented on apps/web/modules/components/entity/editor/id-extension.tsx
> +  onBlur() {
Can you add a comment for this one?

2023-03-20 17:43 UTC, baiirun commented on apps/web/modules/components/entity/editor/table-node.tsx
> +    return types.find(type => type.entityId === typeId) as Triple;
Are we sure this cast isn't hiding a bug?

2023-03-20 17:43 UTC, baiirun commented on apps/web/modules/components/entity/editor/table-node.tsx
> +  }, [types.length, typeId]); // eslint-disable-line react-hooks/exhaustive-deps
Are we sure this won't cause stale data if we get two `types` arrays that are the same length? We could stringify the `types` array if we know it's never very large.

2023-03-20 17:43 UTC, baiirun commented on apps/web/modules/components/entity/editor/table-node.tsx
> +export const TableNodeChildren = React.memo(function TableNodeComponent({
Do you know why it was re-rendering? I'd rather not memoize everything if we know the root cause and if performance isn't actually an issue.

2023-03-20 17:43 UTC, baiirun commented on apps/web/pages/space/[id]/[entityId].tsx
> +      name={props.name}
This is probably okay, but now there's places in the codebase where we read the entity name using triples and places where we don't.

2023-03-20 17:43 UTC, baiirun commented on apps/web/pages/space/[id]/[entityId]/v2.tsx
I'm making changes to the main `[entityId].tsx` page which will probably cause issues when you try and migrate this v2 page over. We might want to get in my versioning changes on the page before we migrate the editor over.

2023-03-20 17:43 UTC, baiirun commented on apps/web/modules/entity/entity-table-store/entity-table-store.ts
> +  initialColumns?: Column[];
Why are we making these optional?

2023-03-21 17:14 UTC, makeitrein commented on apps/web/modules/components/entity/editor/editor.tsx
> +          <SquareButton onClick={() => editor.chain().focus().insertContent('/').run()} icon="plus" />
Yee

2023-03-21 17:14 UTC, makeitrein commented on apps/web/modules/components/entity/editor/id-extension.tsx
> +  onBlur() {
Yee

2023-03-21 17:15 UTC, makeitrein commented on apps/web/pages/space/[id]/[entityId].tsx
> +      name={props.name}
I'll switch it to a computed for cleanliness sake

2023-03-21 17:25 UTC, makeitrein commented on apps/web/modules/components/entity/editor/command-extension.tsx
> +        .filter(v => v.command)
After the command menu opens, we can filter the menu options by typing in it! I left a comment, but we can also just remove this feature...

2023-03-21 17:33 UTC, makeitrein commented on apps/web/modules/components/entity/editor/table-node.tsx
> +  }, [types.length, typeId]); // eslint-disable-line react-hooks/exhaustive-deps
JSON.stringify works!

2023-03-21 17:36 UTC, makeitrein commented on apps/web/modules/components/entity/editor/table-node.tsx
> +export const TableNodeChildren = React.memo(function TableNodeComponent({
Good point. The problem is with `const { types } = useEntityTable();` - if we remove the useMemo and memoized TableNodeChildren component, the table will flicker on every blur. It looks like we can safely remove the other memoizations.

2023-03-21 17:39 UTC, makeitrein commented on apps/web/modules/components/entity/editor/command-list.tsx
> +  const tableItem = items.find(item => item.title === 'Table') as CommandSuggestionItem;
Cool, I extracted tableCommandItem to make sure we don't need this awkward find statement

2023-03-21 17:41 UTC, makeitrein commented on apps/web/modules/components/entity/editor/command-list.tsx
> +    if (!item) {
Good point!

2023-03-22 19:21 UTC, makeitrein commented on apps/web/modules/components/entity/editor/command-list.tsx
> +    }
Nuked - helps with scrolling to the proper item, but since we only have a few blocks to select from, we really don't need it

2023-03-22 19:22 UTC, makeitrein commented on apps/web/modules/entity/entity-table-store/entity-table-store.ts
> +  initialColumns?: Column[];
Whoops, that should not have been committed

2023-03-22 19:29 UTC, makeitrein commented on apps/web/modules/components/entity/editor/command-extension.tsx
> +        },
I attempted to follow the code used in https://github.com/ueberdosis/tiptap/issues/2305 for a more Reacty way of doing things, but Radix doesn't seem to expose a way to position a popover w/o a Popover.Trigger element.

2023-03-22 19:41 UTC, makeitrein commented on apps/web/modules/components/entity/editor/command-list.tsx
> +  useImperativeHandle(ref, () => ({
It feels a little better to hook into ProseMirror's [handleKeyDown](https://prosemirror.net/docs/ref/#view.EditorProps.handleKeyDown) event and call it from their plugin rather than having a global document listener, but both could work!

2023-03-22 20:41 UTC, baiirun approved these changes

2023-03-22 20:42 UTC, merged